version: "2"
services:
  app:
    build: ./app
    restart: always
    links:
      - db
    ports:
      - "8080:8080"

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: secret123
    volumes:
      - ./docker/data/db:/var/lib/mysql